import "./globals.css";
import MainLayout from "./../components/MainLayout";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning={true}
        className="font-[Merriweather] text-white dark:text-gray-300"
      >
        <MainLayout>{children}</MainLayout>
      </body>
    </html>
  );
}
